# Generated by Django 4.1.7 on 2023-02-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Django_Stripe_Api', '0004_remove_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=75.0, max_digits=7),
            preserve_default=False,
        ),
    ]
