# Generated by Django 4.1.7 on 2023-02-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Django_Stripe_Api', '0006_remove_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=7500, max_length=7),
            preserve_default=False,
        ),
    ]
